
[arm]
    # Limits are in raw sensors units
    turret.limit.lo = -85.0
    turret.limit.hi =  90.0
    turret.zeroOffsetRadians = -8.044
    turret.sensorToRadians = 13.541

    # Limits are in degrees
    shoulder.limit.lo =  45.0
    shoulder.limit.hi = 110.0
    shoulder.zeroOffsetRadians = 0.112

    shoulder.pid.p = 0.800
    shoulder.pid.i = 0.003
    shoulder.pid.d = 0.000
    shoulder.pid.tolerance = 0.20

    # Limits are in degrees
    elbow.limit.lo = 25.0
    elbow.limit.hi = 140.0
    elbow.zeroOffsetRadians = -12.219
    elbow.sensorToRadians = 23.445

    # Limits are in degrees
    wrist.limit.lo =   3.0
    wrist.limit.hi = 177.0
    wrist.zeroOffsetRadians = -0.327
    wrist.sensorToRadians = 4.363

    # Limits are in meters
    grip.limit.lo = 0.01
    grip.limit.hi = 0.20
    # Grip closed is considered 0 meters.
    grip.zeroOffsetMeters = -0.55
    grip.sensorToMeters = 1.163
    grip.setpoint.open = 0
    grip.setpoint.close = 0
